### ISSUE TITLE
Widget not clickable

### ISSUE THREAD

**Issue by HonestAbe7** [davidtakac/prognoza#11]
Please consider making the widget clickable so it goes to the app.

**Comment by davidtakac** [comment]
It's clickable on the edges, this is a known bug in Google's Glance library for app widgets. Hopefully they fix it in future versions.

**Comment by HonestAbe7** [comment]
Thanks. It did work.

**Comment by davidtakac** [comment]
I'll leave it open so people know it's being tracked. I'll close it once Google fixes it :smile:

**Comment by HonestAbe7** [comment]
👍

**Comment by davidtakac** [comment]
Fixed in version 3.2.0
