### ISSUE TITLE
Display °C and °F, make current temperature smaller

### ISSUE THREAD

**Issue by muellerto** [davidtakac/prognoza#17]
- the unit of a temperature must be °C or °F, not ° since ° means an angle
- could you please make the temperature a bit smaller? half the size would be good, this would let the other informations much more space on the screen

**Comment by davidtakac** [comment]
Hello, thanks for opening an issue. 
- I think omitting C and F looks better and it's clear enough it refers to degrees Celsius and Fahrenheit.
- The large size of the current temperature is the center-point of the app's design. I'll think about reducing the size if more people feel the same way.

**Comment by davidtakac** [comment]
@muellerto I asked some more people about the current temperature size and it does seem like it's too big. I opened a separate issue for this in #19, we can track it there.
