### ISSUE TITLE
[Feature Request] Remove cities from side menu

### ISSUE THREAD

**Issue by viktoracoric** [davidtakac/prognoza#23]
Hello, I love the app, but one crucial feature is missing, and that is removing the cities from the side menu. Long press then delete or swipe to remove the city feature would be neat.

**Comment by davidtakac** [comment]
Hello, I'm very glad you like the app. And I agree with you, this feature is planned.

**Comment by davidtakac** [comment]
Just pushed version 3.2.0 that has this feature. Thank you again!
