### ISSUE TITLE
Colour the snow icons white instead of blue

### ISSUE THREAD

**Issue by 0-5-0** [davidtakac/prognoza#24]
Excellent app, I love the simplicity of being able to see important info (for me: feels like, rain and snow accumulation) very quickly.

Would it be possible to change the snow flake colour in each of the cloud symbols to white instead of blue? Snow is white afterall (generally speaking) and the rain symbols being blue lines would make snow easier to spot when looking at the various cloud icons, especially the ones where it's a mix of rain and snow under the same cloud.

Thank you

**Comment by davidtakac** [comment]
Hello, I'm really glad you like the app! Thank you. 

Yes, I see what you mean. Snowflakes are hard to differentiate from rain drops because they're currently the same color. The problem with making them white is that they would not be legible in light mode :/ 

Any suggestions? Thing that comes to mind is making them different shades of blue, perhaps.

**Comment by 0-5-0** [comment]
Ah, yes.. light mode.. :)

I do see in light mode the rain is a darker blue compared to snow, I'm not sure if that same blue would be too dark to see in dark mode but having it two different shades would definitely help.

**Comment by 0-5-0** [comment]
That said, are there two different sets of icons, one for light and one for dark (since light mode currently has two shades of blue)?

**Comment by davidtakac** [comment]
> Ah, yes.. light mode.. :)

I know right, who the hell uses light mode anyway? ;) 

> are there two different sets of icons, one for light and one for dark

Yep. Light mode icons are provided as SVGs by MET Norway. But in dark mode, their rain drops, moon and lightning bolt are too dark to be legible, so I changed their colors to create dark mode icons. I'll play around with different shades of blue and see what I come up with

**Comment by davidtakac** [comment]
Somewhere along the line I realized that I can just make the snowflakes white in dark mode and leave them as they are in light mode. Version 3.1.0 has this change, I just pushed it. Please let me know if this fixes your issue :)

**Comment by 0-5-0** [comment]
That makes sense, downloaded 3.1.0 and the new colours look great in dark mode, it's much easier to distinguish the snow from rain especially in the mixed precipitation clouds. Thanks :)

**Comment by davidtakac** [comment]
Awesome, thank you!
