### ISSUE TITLE
Widget doesn't expand to 5xN

### ISSUE THREAD

**Issue by matchboxbananasynergy** [davidtakac/prognoza#26]
The current widget stops expanding after 4 spaces. As a result, if you're using a 5x5 grid, you can't expand it all the way to the end.

**Comment by davidtakac** [comment]
Ah, I don't think I envisioned this happening at all 😄 Thank you, I'll take a look.

**Comment by davidtakac** [comment]
Just pushed version 3.2.0 that fixes this issue and makes widget sizing in general a whole lot better. Feel free to reopen if this is still a problem.

**Comment by matchboxbananasynergy** [comment]
Works great, thanks!
