### ISSUE TITLE
Create space between times on days far from now

### ISSUE THREAD

**Issue by Donkey-Doug** [davidtakac/prognoza#33]
![Screenshot_20221221-234912_Prognoza](https://user-images.githubusercontent.com/50382414/209017678-1d61d054-a221-4fa9-bebd-920f7be18471.png)

I think the times could be spaced out to use the entire width of the screen if there are only 4 times.

**Comment by davidtakac** [comment]
Hi, thank you for the suggestion. I don't think this would make much sense from a user experience standpoint. The spacing should remain consistent so your eyes know where to look between multiple days.
