### ISSUE TITLE
Make widget have rounded corner on Android 11

### ISSUE THREAD

**Issue by scrazzz** [davidtakac/prognoza#36]
Hello, this app looks really good and simple. I want to suggest a small improvement to the widget so that it looks similar to Android 12.

Currently, the widget on Android 11 has a box-shaped widget, which doesn't look good imo. It would be great if the widget would look like the ones on the preview (F-droid app screenshots) with rounded-corners.

Current widget on Android 11:
![amazov2jhf1e7vy3](https://user-images.githubusercontent.com/70033559/209678893-d58198f8-cb82-4225-91c1-842d1b0a36a4.jpg)

**Comment by davidtakac** [comment]
Hello, I totally agree, this is a known bug and a fix is planned. Thank you!

**Comment by davidtakac** [comment]
Should be fixed in 3.3.0, please re-open if it persists
