### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by electr1fy0** [davidtakac/prognoza#42]
Toolbar should fade away when scrolled to the top as it contains nothing and will look cleaner.

**Comment by electr1fy0** [comment]
For reference, exactly how Pixel Launcher's App Drawer Search Bar behaves.

**Comment by davidtakac** [comment]
Hi, thank you for the suggestion. This is how it was in the beginning, but the design looked too flat. I like the pop of color the empty toolbar gives :)
