### ISSUE TITLE
System back button closes app instead of side menu

### ISSUE THREAD

**Issue by userkilled** [davidtakac/prognoza#43]
I could be wrong of course, but you need an action from the seat search menu, when you press the back button, it closes the menu, not exit the application. It's just that I have it all over the screen and it's not so clear that it's not a separate page, but just a menu. 🧠🌀

**Comment by davidtakac** [comment]
I think I saw this bug when I tested on smaller devices but forgot about it in the meantime 😄 Thanks!

**Comment by davidtakac** [comment]
Just pushed 3.4.1 with this addressed. The system back button now closes the drawer instead of the app. This is just a temporary workaround. I'll probably rework the places screen to be a separate destination sometime soon.
