### ISSUE TITLE
Add Weblate for translations

### ISSUE THREAD

**Issue by ghost** [davidtakac/prognoza#47]
Add [Weblate](https://weblate.org/en) for translations.

**Comment by davidtakac** [comment]
Thank you for bringing this up. Unfortunately, it looks like it requires payment unless I self-host it (and I would have to pay to self-host it 😄). 

Other than that, the project is still pretty small, so I don't see the need. Pull requests with new strings.xml files should be fine for now. 

Still, I will keep this in mind if the need for such a service arises.
