### ISSUE TITLE
Widget improvement

### ISSUE THREAD

**Issue by ghost** [davidtakac/prognoza#49]
Widget solid fill looks really out of place for my (and I'm sure a lot of other people's) setup.

It is the only issue that is keeping me (and I'm sure a lot of others) from switching to your app.

Please consider adding a widget transparency selector slider option.

Regards.

![Screenshot_20230226-080251~2](https://user-images.githubusercontent.com/125934998/221379757-bb9a3e71-3e26-4701-9194-831bded00983.png)

**Comment by davidtakac** [comment]
Hello! Yes, I see what you mean. This is mentioned in #28 as well, and it's a planned feature.
