### ISSUE TITLE
missing buzzword: license :)

### ISSUE THREAD

**Issue by IzzySoft** [davidtakac/prognoza#9]
Hi, and thanks for providing your app here for free! I just wondered if it's also libre – but could not find any license, so it's "all rights reserved" :cry: Could you pick and assign a free and libre license, i.e. one improved by OSI/FSF (see [here](https://spdx.org/licenses/) for a nice list)? That'd be great! Thanks in advance.

PS: and apologies for the pun: I had to smile seeing that section of your readme, as indeed I always scowl "buzzwords" when those comprise the only description a project offers. Which means: this pun is yours, and I like it :smile:

**Comment by davidtakac** [comment]
Thank you, fixed in 8b3fc8a. I meant the project to be libre from the start, but I forgot to actually add the license :smile: And I'm glad you liked the buzzwords section! Recruiters like them too, you know how it is :sweat_smile:

**Comment by IzzySoft** [comment]
> Thank you, fixed

Great! Thank you! This enabled me to add your app to my repo. It will [show up here](https://apt.izzysoft.de/fdroid/index/apk/hr.dtakac.prognoza) with the next sync around 7 pm UTC.

> I meant the project to be libre from the start, but I forgot to actually add the license

Hehe, happens – and actually that was what I hoped to be the reason. Thanks for not disappointing me!

> And I'm glad you liked the buzzwords section!

Oh, very much! Finally someone who did it right.

> Recruiters like them too, you know how it is

Believe me, I do! But I never found someone having the perfect way to include them. You won't believe (or maybe you will) how many projects out there have **only** those buzzwords there, and no real description…

So thanks once more! If you like what you see popping up there tomorrow, be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from the Readme.

**Comment by davidtakac** [comment]
I was hoping you'd say that, I love your repo! Thank you very much. I will definitely add the badge once it's up 😄 I just uploaded version 3.0.0 with a bunch of fixes and polishes, it was in the pipeline for a while. 

> You won't believe (or maybe you will) how many projects out there have only those buzzwords there, and no real description…

Oh, I would, I used to do the same thing! Back when I was still new to Android, I often picked the libraries first, and then threw together a project around them. There are *so many* libraries and buzzwords you need to learn if you want to work as an Android developer that it's easy to lose focus.

**Comment by IzzySoft** [comment]
> I love your repo!

:heart_eyes:

> I just uploaded version 3.0.0 with a bunch of fixes and polishes, it was in the pipeline for a while.

Ah, great! Then please check when the app shows up in my repo that this update is there (so you know auto-updates work fine). Not that I expect any problem – but when the chance is there we should use it :wink:

> Oh, I would, I used to do the same thing!

:eyes: :rofl:
